### PR TITLE
fixing frontend condition for decide published article

### PR DESCRIPTION
**Pull request by Buddhima**
### Summary of Changes

Change publishing condition

### Testing Instructions

Create article from backend
Add a menu item and assign article.
Make article's status "published" using workflow

Before: error page though article is published

After: Article shows properly when in published state

### Documentation Changes Required

No

### CODE REVIEW

**Comment by zero-24** [comment]
Looks like drone is not happy ;)

image

**Comment by Buddhima** [comment]
@zero-24 : Can you please help me to figure-out where the issue is?
I failed to find such an occurrence

**Comment by zero-24** [comment]
can you update your branch with the GSoC17_publishing_workflow master branch? Looks like you have a older base ;)

**Comment by Buddhima** [comment]
Thanks a lot @zero-24 , I had to use 0.0.1-basic branch, which should be updated with the master branch. I will ask Janic to first sync 0.0.1-basic with the master

**Pull request merged**
